# Use the official Python base image
FROM python:3.12-slim

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y \
    git \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables to ensure Python output is sent straight to terminal (e.g., logs)
ENV PYTHONUNBUFFERED=1

# Create and set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY . /app/

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose any necessary ports
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]
